name: A workflow for my Hello childrens
on: push

jobs:
  build:
    name: Hello Children Action
    runs-on: debian
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a 
        with:
          MY_NAME: "Joaquin and Julian!" 
